# Generated by Django 2.1 on 2018-08-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_auto_20180809_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazar',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ammount',
            new_name='amount',
        ),
    ]
