# Generated by Django 2.1 on 2018-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phn', models.CharField(max_length=20)),
                ('regi_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
